// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utqpqrllgnhsvkplohal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cXBxcmxsZ25oc3ZrcGxvaGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjAyMzAsImV4cCI6MjA2ODMzNjIzMH0.fjEKGkuiJ0AbhjZ_a5vGAkkp0bc4jGrk0-u3W5k968Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});